### ISSUE TITLE
Release Issues

### ISSUE THREAD

**Issue by shawnfunke** [shawnfunke/injections-google-tasks#1]
#### Description

A list of current issues that need to be fixed for the Google Tasks injection.

#### Tasks

  - [ ] Fix styling for selection
  - [ ] Fix styling for input fields
  - [ ] Fix styling of date input
  - [ ] Fix styling of context menu ripple
  - [ ] Fix description wrap when 3 lines exist but the second one is left empty
  - [ ] Fix styling for task hovering
  - [ ] Fix description mutator when new tasks are added
  - [ ] Fix context menu position on right click
